# LIMPIEZA DE LA BASE DE DATOS

INTRODUCCIÓN: 

PARA EL PRESENTE ANÁLISIS SE HA USADO ESTA BASE DE DATOS PARA SEGMENTAR EL PÚBLICO OBJETIVO ANTE EL LANZAMIENTO DE UN PRODUCTO QUE HA SIDO DISEÑADO PARA PREVENIR SITIUACIONES DE RIESGO ANTE EL ATAQUE DE TIBURONES ASÍ COMO LA ÉPOCA DEL AÑO EN LA QUE SERÍA MÁS FACIL PENETRAR EN EL MERCADO

IMPORTACIÓN DE LA BASE DE DATOS Y LIBRERÍAS

In [54]:
import pandas as pd
import re
import matplotlib

In [55]:
SharksBBDD = pd.read_csv('./GSAF5.csv', engine= "python")

RECUENTO DE VALORES NULOS:

In [56]:
SharksBBDD.isna().sum()

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

BORRADO DE COLUMNAS PRESCINDIBLES PARA EL ESTUDIO

In [57]:

SharksBBDD.drop(['Unnamed: 22', 'Unnamed: 23', 'Time', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'original order', 'Injury', 'Name', 'Species ', 'Investigator or Source'] , axis=1, inplace=True)

In [58]:
SharksBBDD.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Sex ', 'Age', 'Fatal (Y/N)'],
      dtype='object')

SUSTITUIR VALORES NULOS POR "Unknown"

In [59]:
SharknoNa = SharksBBDD[['Case Number', 'Date', 'Year', 'Type','Country', 'Area', 'Location', 'Activity', 'Sex ', 'Age', 'Fatal (Y/N)']].fillna('Unknown')
SharknoNa.head(20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Fatal (Y/N)
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,16,N
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,36,N
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,43,N
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,M,Unknown,N
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,M,Unknown,N
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Unknown,Unknown,N
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,M,60s,N
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,F,51,N
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,M,50,Y
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,F,12,N
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,M,Unknown,N
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,M,9,N
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,M,22,N
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,25,N
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,37,N
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,Unknown,Boucan Canot,Surfing,M,20,N
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,M,49,N
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,M,15,N
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,M,21,N
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,22,N

RECUENTO Y  LIMPIEZA DE LA VARIABLE DATE

In [60]:
SharknoNa['Date'].value_counts()

1957                    11
1942                     9
1956                     8
1958                     7
1950                     7
1941                     7
1949                     6
No date                  6
1940                     5
1970s                    5
Oct-60                   5
1955                     5
No date, Before 1963     5
12-Apr-01                5
28-Jul-95                5
1959                     5
Aug-56                   5
05-Oct-03                5
1954                     5
28-Dec-14                4
14-Jun-12                4
09-Jan-10                4
Before 1906              4
1890                     4
1960                     4
Before 1958              4
1960s                    4
1952                     4
09-Jul-94                4
27-Jul-52                4
                        ..
28-Jul-59                1
Ca. 1911                 1
17-Sep-76                1
19-Jul-10                1
08-Nov-1853              1
10-Feb-75                1
May-32                   1
26-Feb-01                1
Reported 29-Nov-2005     1
11-Dec-13                1
06-Jun-89                1
03-May-16                1
09-Apr-92                1
20-May-01                1
09-Jul-57                1
09-Apr-61                1
14-Mar-84                1
06-Aug-14                1
04-May-11                1
09-Nov-39                1
27-Mar-13                1
07-Dec-52                1
29-May-04                1
03-Jun-62                1
24-Jun-97                1
01-Jan-07                1
15-Nov-04                1
12-Dec-58                1
30-Jun-40                1
14-Aug-60                1
Name: Date, Length: 5128, dtype: int64

In [61]:
def findmes (m):
    m = str(m)
    if len(re.findall('\-\w+\-',m))==0:
        return '-'
    else:
        t= re.findall('\-\w+\-',m)
        return t[0][1:4]

In [62]:
SharknoNa['Date']= SharknoNa['Date'].apply(findmes)

A continuación se eliminarán los elementos Ap-, 26-, 30- y Jut, ya que no queda claro su valor y no suponen un valor representativo

In [63]:
SharknoNa1=SharknoNa1[SharknoNa['Date']!='Ap-']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [64]:
SharknoNa1=SharknoNa1[SharknoNa['Date']!='30-']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [65]:
SharknoNa1=SharknoNa1[SharknoNa['Date']!='Jut']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [66]:
SharknoNa1=SharknoNa1[SharknoNa['Date']!='26-']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [67]:
SharknoNa1['Date'].value_counts()

Jul    72
Jun    60
Aug    49
Sep    48
May    45
Oct    41
-      35
Mar    32
Jan    31
Nov    27
Dec    27
Apr    25
Feb    20
Name: Date, dtype: int64

DADO QUE LA NATURALEZA DE LA INVESTIGACIÓN ES PARA EL LANZAMIENTO DE UN PRODUCTO ES CONVENIENTE ACOTAR LA POBLACIÓN A LAS TRES ÚLTIMAS DÉCADAS DONDE SE ENCUENTRA LA POBLACIÓN ACTUAL

In [69]:
SharknoNa1=SharknoNa1[SharknoNa1['Year']>=1990]
display(SharknoNa1)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Fatal (Y/N)
5,2016.09.15.R,Sep,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Unknown,Unknown,N
7,2016.09.07,Sep,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,F,51,N
9,2016.09.05.b,Sep,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,F,12,N
29,2016.07.17,Jul,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Unknown,Unknown,N
30,2016.07.16.b,Jul,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,F,9,N
31,2016.07.16.a,Jul,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Unknown,F,11,N
34,2016.07.08.R,Jul,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",Wading,F,10,N
38,2016.07.06,Jul,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",Swimming,F,42,N
48,2016.06.14,Jun,2016,Unprovoked,USA,Texas,"Pirates Beach, Galveston",Floating in tube,F,6,N
52,2016.06.05.a,Jun,2016,Unprovoked,AUSTRALIA,Western Australia,Mindarie,Diving,F,60,Y
57,2016.05.29.b,May,2016,Unprovoked,USA,California,"Corona Del Mar, Newport, Orange County",Swimming,F,52,N
59,2016.05.22,May,2016,Unprovoked,USA,Florida,"Vero Beach, Indian River County",Swimming,F,57,N
60,2016.05.21.b,May,2016,Unprovoked,USA,Florida,"St. Petersburg, Pinellas County",Swimming,F,22,N
61,2016.05.21.a,May,2016,Unprovoked,USA,Florida,"Hugenot Beach , Jacksonville, Duval County",Swimming,F,11,N
63,2016.05.15,May,2016,Provoked,USA,Florida,"Boca Raton, Palm Beach County",Teasing a shark,F,23,N
72,2016.04.09,Apr,2016,Unprovoked,NEW CALEDONIA,Grand Terre,Poe Beach,Walking,F,69,Y
76,2016.03.31,Mar,2016,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,46,N
81,2016.03.13,Mar,2016,Invalid,USA,California,"Bolsa Chica State Park, Orange County",Surfing,Unknown,Unknown,N
89,2016.02.12,Feb,2016,Unprovoked,DOMINICAN REPUBLIC,Altagracia Province,"Bavaro Beach, Punta Cana",Wading,F,Unknown,N
92,2016.02.05,Feb,2016,Unprovoked,AUSTRALIA,Queensland,Stradbroke Island,Walking,F,45,N
96,2016.01.25,Jan,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai,",Surfing,F,15,N
104,2015.12.25,Dec,2015,Unprovoked,SPAIN,Grand Canary Island,"Arinaga Beach, Aguimes, Gran Canaria",Swimming,F,38,N
109,2015.12.13,Dec,2015,Boat,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Unknown,Unknown,N
111,2015.12.08,Dec,2015,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Mpande,Swimming / Wading,F,22,N
113,2015.11.15.b,Nov,2015,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",Swimming,F,Unknown,N
116,2015.12.23,Nov,2015,Invalid,USA,Florida,"Paradise Beach, Melbourne, Brevard County",Surfing,F,9,N
118,2015.11.01.b,Nov,2015,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Wading,F,28,N
125,2015.10.17.c,Oct,2015,Unprovoked,MOZAMBIQUE,Inhambane Province,"Nahaduga, Inhambane Bay",Fishing for shrimp,F,35,Y
129,2015.10.09.b,Oct,2015,Unprovoked,USA,South Carolina,"Shipyard Beach Club, Hilton Head Island, Beauf...",Boogie boarding,F,9,N
137,2015.09.26,Sep,2015,Unprovoked,AUSTRALIA,Queensland,"Russel Island, Frankland Group",Snorkeling,F,7,N
...,...,...,...,...,...,...,...,...,...,...,...
2271,1993.06.00,-,1993,Unprovoked,USA,North Carolina,"Hamstead, Pender County",Swimming,F,60,N
2272,1993.05.00.b,-,1993,Unprovoked,HONG KONG,"On the Kowloon penisula, south of Sai Kung",Silverstrand,Unknown,F,Unknown,Y
2273,1993.05.00.a,-,1993,Unprovoked,SOMALIA,Banaadir Region,"Arroyo Beach, Mogadishu",Swimming,F,Unknown,Y
2277,1993.03.17,Mar,1993,Unprovoked,JAPAN,Ehime Prefecture,Iyo,Unknown,Unknown,Unknown,N
2280,1993.03.00,-,1993,Unprovoked,NEW CALEDONIA,South Province,�le de Casey,Swimming,Unknown,Unknown,N
2289,1993.00.00.c,-,1993,Unprovoked,SOMALIA,Banaadir Region,Mogadishu,Unknown,Unknown,Unknown,Y
2290,1993.00.00.b,-,1993,Unprovoked,TONGA,Vava�u,Between Ofu & Fafini Islands,Spearfishing,Unknown,30,N
2291,1993.00.00.a,-,1993,Unprovoked,USA,Florida,"Key West, Monroe County",Snorkeling,Unknown,Unknown,N
2305,1992.10.11,Oct,1992,Unprovoked,BRAZIL,Maranh�o,"Praia de S�o Marcus, S�o Luiz",Boogie boarding,Unknown,Unknown,N
2309,1992.09.11,Sep,1992,Unprovoked,USA,Florida,"South Jetty, New Smyrna Beach, Volusia County",Standing,F,18,N
2312,1992.08.29,Aug,1992,Unprovoked,BAHAMAS,Abaco Islands,Double Breasted Cays,"Snorkeling, carrying a speared fish in her hand",F,34,N
2319,1992.07.21,Jul,1992,Unprovoked,USA,Florida,"Manasota Beach, Sarasota County",Standing,F,42,N
2324,1992.06.19,Jun,1992,Unprovoked,VANUATU,Malampa Province,"Port Sandwich, Malakula",Swimming,F,21,N
2325,1992.06.17,Jun,1992,Boat,JAPAN,Ehime Prefecture,"1.5 km north of Igata-cho, 60 km south of Mats...",Preparing to fish for jack-mackerel,Unknown,Unknown,N
2326,1992.06.00,-,1992,Unprovoked,REUNION,Saint-Paul,Unknown,Diving,Unknown,Unknown,N
2332,1992.03.28,Mar,1992,Unprovoked,USA,Hawaii,"Cannons, at Ha'ena on the north shore of Kaua'...","Surfing, paddling seawards",F,36,N
2335,1992.03.08.b,Mar,1992,Boat,JAPAN,Ehime Prefecture,"Nagahama-cho, 40 km southwest of Matsuyama","Fishing for yellowtail, Seriola quinqueradiata",Unknown,Unknown,N
2346,1992.01.00,-,1992,Invalid,JAPAN,Sea of Japan,Kanazawa?,Unknown,Unknown,Unknown,N
2349,1991.11.26.b,Nov,1991,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,41,Y
2350,1991.11.26.a,Nov,1991,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,Unknown,N
2360,1991.08.12,Aug,1991,Unprovoked,USA,Florida,"Vero Beach, Indian River County",Wading,F,10,N
2362,1991.07.30,Jul,1991,Boat,ITALY,Ligurian Sea,"Portofino, 20 miles offshore, Tigullio Bay, Sa...",Canoeing,F,40,N
2373,1991.06.07.a,Jun,1991,Unprovoked,HONG KONG,Port Shelter,"Silverstrand Beach, near Hung Hau",Swimming,F,65,Y
2376,1991.04.24,Apr,1991,Provoked,BRAZIL,Pernambuco,"Praia de Pau Amarelo, Recife",Fishing,Unknown,Unknown,N
2377,1991.04.16.b,Apr,1991,Provoked,USA,Maryland,Baltimore Aquarium,Diving,Unknown,Unknown,N
2388,1990.11.03,Nov,1990,Unprovoked,USA,California,"Monastery Beach, Carmel Bay, Monterey County",Scuba diving (but on surface),F,Unknown,N
2404,1990.07.22,Jul,1990,Unprovoked,USA,Texas,"Mustang Island State Park, Nueces County",Wading,F,53,N
2406,1990.06.24,Jun,1990,Unprovoked,SOUTH AFRICA,Western Cape Province,Mossel Bay,Scuba diving (but on surface),F,21,Y
2408,1990.05.13,May,1990,Provoked,SOUTH AFRICA,KwaZulu-Natal,Protea Reef,Fishing,Unknown,Unknown,N
2409,1990.05.10,May,1990,Unprovoked,AUSTRALIA,Queensland,Outer Barrier Reef near Port Douglas,Snorkeling,F,30,N

RECUENTO Y LIMPIEZA DE LA VARIABLE AGE

In [70]:
SharknoNa1['Age'].value_counts()

Unknown    201
13          18
14          14
10          12
15          12
12          11
20          11
9           10
19          10
21           9
22           9
17           9
34           9
29           8
11           8
38           8
30           7
7            7
60           7
18           6
42           6
35           6
23           5
44           5
28           5
37           5
40           5
41           5
45           4
6            4
          ...
26           4
50           4
24           4
36           4
70           3
58           3
51           3
8            3
48           3
56           3
43           3
27           2
55           2
32           2
65           2
52           2
57           2
59           2
25           2
33           1
69           1
46           1
53           1
54           1
61           1
31           1
77           1
49           1
68           1
39           1
Name: Age, Length: 63, dtype: int64

In [71]:
def findage (t):
    
    t = str(t)
    b = re.findall ('\d+', t)
    
    if len(b) == 1:
        return b[0]
    else:
        return 'Unknown'

In [72]:
SharknoNa1['Age']= SharknoNa1['Age'].apply(findage)

RECUENTO Y LIMPIEZA DE LA VARIABLE SEX

In [74]:
SharknoNa1['Sex '].value_counts()

F          363
Unknown    147
M            2
Name: Sex , dtype: int64

In [75]:
print(set(SharknoNa1['Sex ']))

{'Unknown', 'F', 'M '}

In [76]:
SharknoNa1['Sex '].value_counts()

F          363
Unknown    147
M            2
Name: Sex , dtype: int64

In [77]:
SharknoNa1=SharknoNa1[SharknoNa['Sex ']!='lli']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [78]:
SharknoNa1=SharknoNa1[SharknoNa['Sex ']!='M']

/home/javier/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

RECUENTO DE LA VARIABLE ACTIVITY

In [80]:
SharknoNa1['Activity'].value_counts()

Swimming                                                            93
Surfing                                                             61
Unknown                                                             48
Wading                                                              41
Snorkeling                                                          33
Fishing                                                             30
Standing                                                            15
Spearfishing                                                        11
Diving                                                              10
Boogie boarding                                                      9
Scuba diving                                                         7
Boogie Boarding                                                      6
Walking                                                              6
Body boarding                                                        4
Body surfing                                                         4
Kayaking                                                             4
Playing                                                              3
Murder                                                               3
Rowing                                                               3
Stand-Up Paddleboarding                                              2
Surf skiing                                                          2
Fishing for whiting                                                  2
Surfing, paddling seawards                                           2
Fishing                                                              2
Scuba diving (but on surface)                                        2
Paddle boarding                                                      2
Feeding fish                                                         2
Sea Disaster                                                         2
Jumping                                                              2
Canoeing                                                             2
                                                                    ..
In water with diving seabirds                                        1
Treading water                                                       1
Preparing to fish for jack-mackerel                                  1
Reviving a sedated shark                                             1
Kneeling in the water                                                1
Shark tagging                                                        1
SCUBA Diving                                                         1
Towing rubber dinghy                                                 1
Cruising                                                             1
Fishing for shrimp                                                   1
Standing in inner tube                                               1
Crouching in 2' of water                                             1
Swimming                                                             1
Spearfishing, holding mesh bag with speared fish                     1
Fishing for yellowtail, Seriola quinqueradiata                       1
Floating on raft                                                     1
Petting captive sharks                                               1
Holding onto an inflatable boat                                      1
Fishingat                                                            1
Sailing                                                              1
Swimming, wearing black wetsuit & swim fins                          1
Air disaster. Flash Airlines Boeing 737 crashed into the Red Sea     1
Swimming with boogie board                                           1
Rescuing                                                             1
Surfing & filming dolphins                                           1
"Riding waves on a board"                                            1
Swimming / jumping off a jetty                                       1
Jumped into the water                                                1
Fell into the water                                                  1
Attempting to drive shark away from sailing regatta                  1
Name: Activity, Length: 126, dtype: int64

RECUENTO DE LA VARIABLE YEAR

In [83]:
SharknoNa1['Year'].value_counts()

2007    34
2014    33
2015    29
2012    26
2005    25
2000    23
2006    22
2004    22
2010    22
2009    22
2016    21
2013    20
1993    20
2001    20
2011    19
2008    19
1996    17
2003    17
1994    16
2002    15
1999    14
1995    14
1997    11
1992    10
1998     9
1991     7
1990     5
Name: Year, dtype: int64

In [84]:
SharknoNa2 = SharknoNa1

In [85]:
SharknoNa2.to_csv('./Database1.csv')

DATAFRAME FINAL

In [89]:
display(SharknoNa2)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Fatal (Y/N)
5,2016.09.15.R,Sep,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Unknown,Unknown,N
7,2016.09.07,Sep,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,F,51,N
9,2016.09.05.b,Sep,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,F,12,N
29,2016.07.17,Jul,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Unknown,Unknown,N
30,2016.07.16.b,Jul,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,F,9,N
31,2016.07.16.a,Jul,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Unknown,F,11,N
34,2016.07.08.R,Jul,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",Wading,F,10,N
38,2016.07.06,Jul,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",Swimming,F,42,N
48,2016.06.14,Jun,2016,Unprovoked,USA,Texas,"Pirates Beach, Galveston",Floating in tube,F,6,N
52,2016.06.05.a,Jun,2016,Unprovoked,AUSTRALIA,Western Australia,Mindarie,Diving,F,60,Y
57,2016.05.29.b,May,2016,Unprovoked,USA,California,"Corona Del Mar, Newport, Orange County",Swimming,F,52,N
59,2016.05.22,May,2016,Unprovoked,USA,Florida,"Vero Beach, Indian River County",Swimming,F,57,N
60,2016.05.21.b,May,2016,Unprovoked,USA,Florida,"St. Petersburg, Pinellas County",Swimming,F,22,N
61,2016.05.21.a,May,2016,Unprovoked,USA,Florida,"Hugenot Beach , Jacksonville, Duval County",Swimming,F,11,N
63,2016.05.15,May,2016,Provoked,USA,Florida,"Boca Raton, Palm Beach County",Teasing a shark,F,23,N
72,2016.04.09,Apr,2016,Unprovoked,NEW CALEDONIA,Grand Terre,Poe Beach,Walking,F,69,Y
76,2016.03.31,Mar,2016,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,46,N
81,2016.03.13,Mar,2016,Invalid,USA,California,"Bolsa Chica State Park, Orange County",Surfing,Unknown,Unknown,N
89,2016.02.12,Feb,2016,Unprovoked,DOMINICAN REPUBLIC,Altagracia Province,"Bavaro Beach, Punta Cana",Wading,F,Unknown,N
92,2016.02.05,Feb,2016,Unprovoked,AUSTRALIA,Queensland,Stradbroke Island,Walking,F,45,N
96,2016.01.25,Jan,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai,",Surfing,F,15,N
104,2015.12.25,Dec,2015,Unprovoked,SPAIN,Grand Canary Island,"Arinaga Beach, Aguimes, Gran Canaria",Swimming,F,38,N
109,2015.12.13,Dec,2015,Boat,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Unknown,Unknown,N
111,2015.12.08,Dec,2015,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Mpande,Swimming / Wading,F,22,N
113,2015.11.15.b,Nov,2015,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",Swimming,F,Unknown,N
116,2015.12.23,Nov,2015,Invalid,USA,Florida,"Paradise Beach, Melbourne, Brevard County",Surfing,F,9,N
118,2015.11.01.b,Nov,2015,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Wading,F,28,N
125,2015.10.17.c,Oct,2015,Unprovoked,MOZAMBIQUE,Inhambane Province,"Nahaduga, Inhambane Bay",Fishing for shrimp,F,35,Y
129,2015.10.09.b,Oct,2015,Unprovoked,USA,South Carolina,"Shipyard Beach Club, Hilton Head Island, Beauf...",Boogie boarding,F,9,N
137,2015.09.26,Sep,2015,Unprovoked,AUSTRALIA,Queensland,"Russel Island, Frankland Group",Snorkeling,F,7,N
...,...,...,...,...,...,...,...,...,...,...,...
2271,1993.06.00,-,1993,Unprovoked,USA,North Carolina,"Hamstead, Pender County",Swimming,F,60,N
2272,1993.05.00.b,-,1993,Unprovoked,HONG KONG,"On the Kowloon penisula, south of Sai Kung",Silverstrand,Unknown,F,Unknown,Y
2273,1993.05.00.a,-,1993,Unprovoked,SOMALIA,Banaadir Region,"Arroyo Beach, Mogadishu",Swimming,F,Unknown,Y
2277,1993.03.17,Mar,1993,Unprovoked,JAPAN,Ehime Prefecture,Iyo,Unknown,Unknown,Unknown,N
2280,1993.03.00,-,1993,Unprovoked,NEW CALEDONIA,South Province,�le de Casey,Swimming,Unknown,Unknown,N
2289,1993.00.00.c,-,1993,Unprovoked,SOMALIA,Banaadir Region,Mogadishu,Unknown,Unknown,Unknown,Y
2290,1993.00.00.b,-,1993,Unprovoked,TONGA,Vava�u,Between Ofu & Fafini Islands,Spearfishing,Unknown,30,N
2291,1993.00.00.a,-,1993,Unprovoked,USA,Florida,"Key West, Monroe County",Snorkeling,Unknown,Unknown,N
2305,1992.10.11,Oct,1992,Unprovoked,BRAZIL,Maranh�o,"Praia de S�o Marcus, S�o Luiz",Boogie boarding,Unknown,Unknown,N
2309,1992.09.11,Sep,1992,Unprovoked,USA,Florida,"South Jetty, New Smyrna Beach, Volusia County",Standing,F,18,N
2312,1992.08.29,Aug,1992,Unprovoked,BAHAMAS,Abaco Islands,Double Breasted Cays,"Snorkeling, carrying a speared fish in her hand",F,34,N
2319,1992.07.21,Jul,1992,Unprovoked,USA,Florida,"Manasota Beach, Sarasota County",Standing,F,42,N
2324,1992.06.19,Jun,1992,Unprovoked,VANUATU,Malampa Province,"Port Sandwich, Malakula",Swimming,F,21,N
2325,1992.06.17,Jun,1992,Boat,JAPAN,Ehime Prefecture,"1.5 km north of Igata-cho, 60 km south of Mats...",Preparing to fish for jack-mackerel,Unknown,Unknown,N
2326,1992.06.00,-,1992,Unprovoked,REUNION,Saint-Paul,Unknown,Diving,Unknown,Unknown,N
2332,1992.03.28,Mar,1992,Unprovoked,USA,Hawaii,"Cannons, at Ha'ena on the north shore of Kaua'...","Surfing, paddling seawards",F,36,N
2335,1992.03.08.b,Mar,1992,Boat,JAPAN,Ehime Prefecture,"Nagahama-cho, 40 km southwest of Matsuyama","Fishing for yellowtail, Seriola quinqueradiata",Unknown,Unknown,N
2346,1992.01.00,-,1992,Invalid,JAPAN,Sea of Japan,Kanazawa?,Unknown,Unknown,Unknown,N
2349,1991.11.26.b,Nov,1991,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,41,Y
2350,1991.11.26.a,Nov,1991,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,F,Unknown,N
2360,1991.08.12,Aug,1991,Unprovoked,USA,Florida,"Vero Beach, Indian River County",Wading,F,10,N
2362,1991.07.30,Jul,1991,Boat,ITALY,Ligurian Sea,"Portofino, 20 miles offshore, Tigullio Bay, Sa...",Canoeing,F,40,N
2373,1991.06.07.a,Jun,1991,Unprovoked,HONG KONG,Port Shelter,"Silverstrand Beach, near Hung Hau",Swimming,F,65,Y
2376,1991.04.24,Apr,1991,Provoked,BRAZIL,Pernambuco,"Praia de Pau Amarelo, Recife",Fishing,Unknown,Unknown,N
2377,1991.04.16.b,Apr,1991,Provoked,USA,Maryland,Baltimore Aquarium,Diving,Unknown,Unknown,N
2388,1990.11.03,Nov,1990,Unprovoked,USA,California,"Monastery Beach, Carmel Bay, Monterey County",Scuba diving (but on surface),F,Unknown,N
2404,1990.07.22,Jul,1990,Unprovoked,USA,Texas,"Mustang Island State Park, Nueces County",Wading,F,53,N
2406,1990.06.24,Jun,1990,Unprovoked,SOUTH AFRICA,Western Cape Province,Mossel Bay,Scuba diving (but on surface),F,21,Y
2408,1990.05.13,May,1990,Provoked,SOUTH AFRICA,KwaZulu-Natal,Protea Reef,Fishing,Unknown,Unknown,N
2409,1990.05.10,May,1990,Unprovoked,AUSTRALIA,Queensland,Outer Barrier Reef near Port Douglas,Snorkeling,F,30,N